### ISSUE TITLE
Resolution smearing

### ISSUE THREAD

**Issue by andped10** [EasyScience/EasyReflectometryLib#110]
Implementation issues:
#127 
#128 
#130 

Currently, we only support a constant Gaussian q-resolution function. However, many reflectometry analysis libraries support q-dependent Gaussian resolution and even arbitrary function resolutions.

https://github.com/easyScience/EasyReflectometryLib/issues/4
https://github.com/easyScience/EasyReflectometryLib/issues/47

The resolution data is a part of the orso format.  The 4th column contains sQ.  When a orso file is read the resolution can be fetched by.  Notice that the sQ is variance and the read value is squared value:
```
from EasyReflectometry.data import load
fpath='.\\tests\\_static\\test_example1.ort'
orso = load(fpath)
np.sqrt(orso['data']['R_spin_up'].variances)
```

**Comment by andped10** [comment]
From Jos:
I just re-found this paper which is a (very) detailed explanation of resolution for a neutron reflectometer
https://journals.iucr.org/paper?rg5037
It may be worth a read if you want an understanding of what is/should/can be done

**Comment by andped10** [comment]
Refnx
![image](https://github.com/EasyScience/EasyReflectometryLib/assets/48797331/e1976586-8783-4d10-9f0d-40769e725084)

**Comment by andped10** [comment]
refl1d
![image](https://github.com/EasyScience/EasyReflectometryLib/assets/48797331/021fd726-90d3-46c5-9502-8d06e96a2d34)

**Comment by andped10** [comment]
Code changes should probably only be done in `calculators`.   The specific code is `calculator_base.py` and the specific `wrappers`

**Comment by andped10** [comment]
@jfkcooper how is the shape of the resolution?
I am asking because we have to be able to determine the resolution at an arbitrary point from a provided set of discrete data points.  

Is it correct to assume that the function is smooth and one can simply determine the value from a linear interpolation between the two neighboring provided data-points.  Or is the shape more step-wise and we would have to use the "plain" value of the nearest provided data-point?

Please let me know if my question is not clear enough.

**Comment by jfkcooper** [comment]
I think that it will be a reasonable assumption to take it as smooth and approximating it as a linear interpolation is fine.

**Comment by andped10** [comment]
Done by #141
